language: c
script: autoreconf -fi && ./configure --with-alsa --with-avahi --with-ssl=openssl --with-metadata --with-soxr --with-systemv && make
branches:
  only:
    - development
addons:
  apt:
    packages:
    - libdaemon-dev
    - libasound2-dev
    - libpopt-dev
    - libconfig-dev
