language: c
script: autoreconf -fi && ./configure --with-alsa --with-avahi --with-ssl=openssl --with-metadata --with-soxr --with-systemv && make
branches:
  only:
    - development
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libdaemon-dev
addons:
  apt:
    packages:
    - libasound2-dev
    - libpopt-dev
    - libconfig-dev
